package pe.edu.vg.app.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import jakarta.persistence.*;
import java.math.BigDecimal;

@Entity
@Table(name = "Menu")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Menu {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "DishID")
    private Long dishID;

    @Column(name = "Dish_Name", nullable = false, length = 50)
    private String dishName;

    @Column(name = "Description", columnDefinition = "CLOB")
    private String description;

    @Column(name = "Price", nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    @Column(name = "Status", nullable = false, length = 8)
    private String status = "activo";

    @Column(name = "CategoryID")
    private Long categoryID;

    // Getters and setters are generated by Lombok
}