package pe.edu.vg.app.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "Orders")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Order {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "OrderID")
    private Long orderID;

    @Column(name = "Employee_ID")
    private Long employeeID;

    @Column(name = "Table_ID")
    private Long tableID;

    @Column(name = "Date_Time")
    private LocalDateTime dateTime;

    @Column(name = "Status", length = 10)
    private String status;

    // Getters and setters are generated by Lombok
}
