package pe.edu.vg.app.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

import jakarta.persistence.*;

@Entity
@Table(name = "Tables")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TableCL {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "TableID")
    private Long tableID;

    @Column(name = "Table_Number")
    private Integer tableNumber;

    @Column(name = "Capacity")
    private Integer capacity;

    @Column(name = "Status", length = 8)
    private String status;

    // Getters and setters are generated by Lombok
}